name: molecule
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_emoji: ^2.4.0
  flutter_svg: ^1.1.1+1
  hooks_riverpod: ^1.0.4
  url_launcher: ^6.1.5
  font_awesome_flutter: ^10.1.0
  yaml: ^3.1.1
  json2yaml: ^3.0.0
  ms_undraw: ^3.1.0+2
  file_picker: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/svg/ # used for images
    - assets/examples/ # used for default configs
    - assets/logo/ # used branding
  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: fonts/NotoColorEmoji.ttf
    - family: OpenSans
      fonts: 
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

