name: Release new version

on: pull_request

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get next version
      id: get_next_version
      uses: thenativeweb/get-next-version@2.0.0
    - name: Show the next version
      run: |
        echo ${{ steps.get_next_version.outputs.version }}
        echo ${{ steps.get_next_version.outputs.hasNextVersion }}
    - name: Create release
      if: ${{steps.get_next_version.outputs.hasNextVersion == 'true' }}
      run: |
        NEXT_VERSION = ${{ steps.get_next_version.outputs.version }}
        git tag $NEXT_VERSION
        git push origin $NEXT_VERSION
